
import { Role } from '../types';

export interface CapabilityItem {
  id: string;
  label: string;
  description: string;
  category: string;
}

export const CAPABILITIES: CapabilityItem[] = [
  // 1. Project Management
  { id: 'proj:create', label: 'Create Project', description: 'Create new project profiles', category: 'PROJECTS' },
  { id: 'proj:edit', label: 'Edit Project', description: 'Edit project details', category: 'PROJECTS' },
  { id: 'proj:archive', label: 'Archive Project', description: 'Deactivate projects', category: 'PROJECTS' },
  { id: 'proj:view_all', label: 'View All Projects', description: 'See all projects in tenant', category: 'PROJECTS' },
  { id: 'proj:assign_roles', label: 'Assign Roles', description: 'Assign project roles to users', category: 'PROJECTS' },
  { id: 'proj:set_checklists', label: 'Manage Checklists', description: 'Load and manage setup checklists', category: 'PROJECTS' },
  { id: 'proj:view_financials', label: 'View Financials', description: 'View project health and RAG status', category: 'PROJECTS' },
  { id: 'proj:delete', label: 'Delete Project', description: 'Permanent deletion of project data', category: 'PROJECTS' },

  // 2. BOQ & Quantity Management
  { id: 'boq:import', label: 'Import BOQ', description: 'Import BOQ from Excel/CSV', category: 'BOQ' },
  { id: 'boq:edit_contract', label: 'Edit Contract Qty', description: 'Modify original contract quantities', category: 'BOQ' },
  { id: 'boq:set_surveyed', label: 'Set Surveyed Qty', description: 'Update surveyed/actual quantities', category: 'BOQ' },
  { id: 'boq:view_recipes', label: 'View Recipes', description: 'View resource build-ups for BOQ items', category: 'BOQ' },
  { id: 'boq:confirm_recipe', label: 'Confirm Recipe', description: 'Lock/Confirm recipe for an item', category: 'BOQ' },
  { id: 'boq:create_section', label: 'Create Section', description: 'Create new BOQ sections/WBS', category: 'BOQ' },
  { id: 'boq:assign_section', label: 'Assign Section', description: 'Move items between sections', category: 'BOQ' },
  { id: 'boq:view_actuals', label: 'View Actuals', description: 'Compare contract vs actual quantities', category: 'BOQ' },
  { id: 'boq:export', label: 'Export BOQ', description: 'Export BOQ data to Excel', category: 'BOQ' },
  { id: 'boq:add_item', label: 'Add BOQ Item', description: 'Manually add new items to BOQ', category: 'BOQ' },
  { id: 'boq:delete_item', label: 'Delete BOQ Item', description: 'Remove items from BOQ', category: 'BOQ' },
  { id: 'boq:tag_trade', label: 'Tag Trade', description: 'Assign trade groups to BOQ items', category: 'BOQ' },
  { id: 'boq:manage_baseline', label: 'Manage Baseline', description: 'Set and lock BOQ baselines', category: 'BOQ' },
  { id: 'boq:survey_audit', label: 'Survey Audit', description: 'View history of quantity changes', category: 'BOQ' },

  // 3. Trade Library
  { id: 'trade:view_global', label: 'View Global Trades', description: 'Access platform-wide trade recipes', category: 'TRADES' },
  { id: 'trade:create_company', label: 'Create Company Trade', description: 'Add new trades to company library', category: 'TRADES' },
  { id: 'trade:edit_company', label: 'Edit Company Trade', description: 'Modify company-specific recipes', category: 'TRADES' },
  { id: 'trade:promote', label: 'Promote to Global', description: 'Request trade to be global (God only)', category: 'TRADES' },
  { id: 'trade:import', label: 'Import Trades', description: 'Bulk import trade recipes from Excel', category: 'TRADES' },
  { id: 'trade:archive', label: 'Archive Trade', description: 'Deactivate trade items', category: 'TRADES' },
  { id: 'trade:manage_groups', label: 'Manage Trade Groups', description: 'Create and edit trade categories', category: 'TRADES' },
  { id: 'trade:view_goal', label: 'View Goal Rates', description: 'See target rates for trades', category: 'TRADES' },
  { id: 'trade:view_unit', label: 'View Unit Rates', description: 'See calculated unit rates', category: 'TRADES' },
  { id: 'trade:link_material', label: 'Link Materials', description: 'Add materials to trade recipes', category: 'TRADES' },
  { id: 'trade:link_labour', label: 'Link Labour', description: 'Add labour items to trade recipes', category: 'TRADES' },
  { id: 'trade:link_equip', label: 'Link Equipment', description: 'Add equipment to trade recipes', category: 'TRADES' },
  { id: 'trade:global_edit', label: 'Edit Global Trades', description: 'Modify global library (God only)', category: 'TRADES' },
  { id: 'trade:audit', label: 'Trade Audit', description: 'View change history for recipes', category: 'TRADES' },

  // 4. Resource Library
  { id: 'res:mat_view', label: 'View Materials', description: 'Browse material library', category: 'RESOURCES' },
  { id: 'res:mat_manage', label: 'Manage Materials', description: 'CRUD operations on materials', category: 'RESOURCES' },
  { id: 'res:labour_view', label: 'View Labour', description: 'Browse labour library', category: 'RESOURCES' },
  { id: 'res:labour_manage', label: 'Manage Labour', description: 'CRUD operations on labour', category: 'RESOURCES' },
  { id: 'res:equip_view', label: 'View Equipment', description: 'Browse equipment library', category: 'RESOURCES' },
  { id: 'res:equip_manage', label: 'Manage Equipment', description: 'CRUD operations on equipment', category: 'RESOURCES' },
  { id: 'res:veh_view', label: 'View Vehicles', description: 'Browse vehicle library', category: 'RESOURCES' },
  { id: 'res:veh_manage', label: 'Manage Vehicles', description: 'CRUD operations on vehicles', category: 'RESOURCES' },
  { id: 'res:fuel_view', label: 'View Fuel', description: 'Browse fuel library', category: 'RESOURCES' },
  { id: 'res:fuel_manage', label: 'Manage Fuel', description: 'CRUD operations on fuel', category: 'RESOURCES' },
  { id: 'res:subcon_view', label: 'View Subcontractors', description: 'Browse subcontractor library', category: 'RESOURCES' },
  { id: 'res:subcon_manage', label: 'Manage Subcontractors', description: 'CRUD operations on subcons', category: 'RESOURCES' },
  { id: 'res:import_all', label: 'Import Resources', description: 'Bulk import from Excel', category: 'RESOURCES' },
  { id: 'res:set_rates', label: 'Set Rates', description: 'Update resource base rates', category: 'RESOURCES' },
  { id: 'res:global_consume', label: 'Clone from Global', description: 'Clone global resources to company', category: 'RESOURCES' },
  { id: 'res:global_manage', label: 'Manage Global Resources', description: 'Edit global library (God only)', category: 'RESOURCES' },
  { id: 'res:tag_category', label: 'Tag Categories', description: 'Manage resource categorization', category: 'RESOURCES' },
  { id: 'res:archive', label: 'Archive Resource', description: 'Deactivate resources', category: 'RESOURCES' },
  { id: 'res:audit', label: 'Resource Audit', description: 'View rate change history', category: 'RESOURCES' },
  { id: 'res:view_origins', label: 'View Origins', description: 'See source of global data', category: 'RESOURCES' },

  // 5. Planning & Schedule
  { id: 'plan:view', label: 'View Schedule', description: 'View project Gantt and schedule', category: 'PLANNING' },
  { id: 'plan:edit_dates', label: 'Edit Dates', description: 'Modify task start/end dates', category: 'PLANNING' },
  { id: 'plan:sequence', label: 'Manage Sequence', description: 'Edit task dependencies/links', category: 'PLANNING' },
  { id: 'plan:set_output', label: 'Set Output Rates', description: 'Adjust planned daily outputs', category: 'PLANNING' },
  { id: 'plan:lock_baseline', label: 'Lock Baseline', description: 'Set project schedule baseline', category: 'PLANNING' },
  { id: 'plan:view_baseline', label: 'View Baseline', description: 'Compare current vs baseline', category: 'PLANNING' },
  { id: 'plan:reset', label: 'Reset Schedule', description: 'Clear and restart planning', category: 'PLANNING' },
  { id: 'plan:critical_path', label: 'View Critical Path', description: 'Highlight critical tasks', category: 'PLANNING' },
  { id: 'plan:update_progress', label: 'Update Progress', description: 'Manually update task % complete', category: 'PLANNING' },
  { id: 'plan:manage_sections', label: 'Manage Sections', description: 'Create and edit schedule sections', category: 'PLANNING' },
  { id: 'plan:view_upcoming', label: 'View Upcoming', description: 'See tasks starting soon', category: 'PLANNING' },
  { id: 'plan:export_gantt', label: 'Export Gantt', description: 'Export schedule to PDF/Excel', category: 'PLANNING' },
  { id: 'plan:manpower_req', label: 'View Manpower Req', description: 'See manpower demand histogram', category: 'PLANNING' },
  { id: 'plan:material_req', label: 'View Material Req', description: 'See material demand over time', category: 'PLANNING' },
  { id: 'plan:equip_req', label: 'View Equip Req', description: 'See equipment demand over time', category: 'PLANNING' },

  // 6. Daily Reports & Site Execution
  { id: 'daily:submit', label: 'Submit Daily Report', description: 'Create and submit site reports', category: 'DAILY' },
  { id: 'daily:view_own', label: 'View Own Reports', description: 'See reports created by user', category: 'DAILY' },
  { id: 'daily:view_project', label: 'View Project Reports', description: 'See all reports for project', category: 'DAILY' },
  { id: 'daily:edit_draft', label: 'Edit Drafts', description: 'Modify unsubmitted reports', category: 'DAILY' },
  { id: 'daily:emergency_edit', label: 'Emergency Edit', description: 'Edit approved reports (Admin only)', category: 'DAILY' },
  { id: 'daily:force_approve', label: 'Force Approve', description: 'Bypass approval chain', category: 'DAILY' },
  { id: 'daily:view_edits', label: 'View Edit History', description: 'See audit log of report changes', category: 'DAILY' },
  { id: 'daily:log_manpower', label: 'Log Manpower', description: 'Record daily manpower presence', category: 'DAILY' },
  { id: 'daily:log_equip', label: 'Log Equipment', description: 'Record daily equipment usage', category: 'DAILY' },
  { id: 'daily:log_fuel', label: 'Log Fuel', description: 'Record daily fuel consumption', category: 'DAILY' },
  { id: 'daily:log_subcon', label: 'Log Subcon', description: 'Record subcontractor progress', category: 'DAILY' },
  { id: 'daily:log_weather', label: 'Log Weather', description: 'Record daily weather conditions', category: 'DAILY' },
  { id: 'daily:attach_photo', label: 'Attach Photos', description: 'Upload site photos to reports', category: 'DAILY' },
  { id: 'daily:view_snapshot', label: 'View Snapshots', description: 'See financial/quantity snapshots', category: 'DAILY' },
  { id: 'daily:delete', label: 'Delete Report', description: 'Remove site reports', category: 'DAILY' },

  // 7. Alerts & Incidents
  { id: 'alert:view', label: 'View Alerts', description: 'Access project alert dashboard', category: 'ALERTS' },
  { id: 'alert:create_manual', label: 'Create Manual Alert', description: 'Flag issues manually', category: 'ALERTS' },
  { id: 'alert:dismiss', label: 'Dismiss Alert', description: 'Acknowledge and close alerts', category: 'ALERTS' },
  { id: 'alert:set_thresholds', label: 'Set Thresholds', description: 'Configure variance triggers', category: 'ALERTS' },
  { id: 'alert:load_presets', label: 'Load Presets', description: 'Load standard alert configurations', category: 'ALERTS' },
  { id: 'alert:view_variance', label: 'View Variance', description: 'See detailed cost/qty variance', category: 'ALERTS' },
  { id: 'alert:view_budget', label: 'View Budget Alerts', description: 'See budget-related warnings', category: 'ALERTS' },
  { id: 'alert:view_contract', label: 'View Contract Alerts', description: 'See contract-related warnings', category: 'ALERTS' },
  { id: 'alert:assign', label: 'Assign Alert', description: 'Assign alerts to specific users', category: 'ALERTS' },
  { id: 'alert:comment', label: 'Comment on Alert', description: 'Add notes to alert history', category: 'ALERTS' },
  { id: 'alert:escalate', label: 'Escalate Alert', description: 'Move alert up management chain', category: 'ALERTS' },
  { id: 'alert:view_history', label: 'View Alert History', description: 'See audit log of alerts', category: 'ALERTS' },
  { id: 'alert:export', label: 'Export Alerts', description: 'Export alert data to Excel', category: 'ALERTS' },
  { id: 'alert:ncr_manage', label: 'Manage NCRs', description: 'Create and track Non-Conformance Reports', category: 'ALERTS' },

  // 8. Procurement — Demand & RFQ
  { id: 'proc:view_demand', label: 'View Demand', description: 'See project material demand', category: 'PROCUREMENT' },
  { id: 'proc:create_rfq', label: 'Create RFQ', description: 'Generate Request for Quotations', category: 'PROCUREMENT' },
  { id: 'proc:edit_rfq', label: 'Edit RFQ', description: 'Modify RFQ details', category: 'PROCUREMENT' },
  { id: 'proc:send_rfq', label: 'Send RFQ', description: 'Issue RFQs to suppliers', category: 'PROCUREMENT' },
  { id: 'proc:view_bids', label: 'View Bids', description: 'See supplier quotations', category: 'PROCUREMENT' },
  { id: 'proc:compare_bids', label: 'Compare Bids', description: 'Access bid comparison matrix', category: 'PROCUREMENT' },
  { id: 'proc:select_vendor', label: 'Select Vendor', description: 'Approve vendor selection', category: 'PROCUREMENT' },
  { id: 'proc:approve_rfq', label: 'Approve RFQ', description: 'Final approval for RFQ issuance', category: 'PROCUREMENT' },
  { id: 'proc:view_all_rfq', label: 'View All RFQs', description: 'See all RFQs in tenant', category: 'PROCUREMENT' },
  { id: 'proc:cancel_rfq', label: 'Cancel RFQ', description: 'Void active RFQs', category: 'PROCUREMENT' },
  { id: 'proc:track_pipeline', label: 'Track Pipeline', description: 'See procurement status pipeline', category: 'PROCUREMENT' },
  { id: 'proc:manage_types', label: 'Manage Types', description: 'Configure procurement categories', category: 'PROCUREMENT' },
  { id: 'proc:view_certified', label: 'View Certified', description: 'See pre-qualified suppliers', category: 'PROCUREMENT' },
  { id: 'proc:demand_manual', label: 'Manual Demand', description: 'Create demand without BOQ link', category: 'PROCUREMENT' },
  { id: 'proc:rfq_docs', label: 'Manage RFQ Docs', description: 'Attach specs/drawings to RFQs', category: 'PROCUREMENT' },
  { id: 'proc:supplier_invite', label: 'Invite Supplier', description: 'Invite new vendors to bid', category: 'PROCUREMENT' },
  { id: 'proc:audit', label: 'Procurement Audit', description: 'View history of RFQ process', category: 'PROCUREMENT' },

  // 9. Purchase Orders
  { id: 'po:create', label: 'Create PO', description: 'Generate Purchase Orders', category: 'PURCHASE_ORDERS' },
  { id: 'po:edit', label: 'Edit PO', description: 'Modify PO details', category: 'PURCHASE_ORDERS' },
  { id: 'po:approve', label: 'Approve PO', description: 'Final approval for POs', category: 'PURCHASE_ORDERS' },
  { id: 'po:issue', label: 'Issue PO', description: 'Send PO to supplier', category: 'PURCHASE_ORDERS' },
  { id: 'po:view_all', label: 'View All POs', description: 'See all POs in tenant', category: 'PURCHASE_ORDERS' },
  { id: 'po:cancel', label: 'Cancel PO', description: 'Void issued POs', category: 'PURCHASE_ORDERS' },
  { id: 'po:close', label: 'Close PO', description: 'Mark PO as completed', category: 'PURCHASE_ORDERS' },
  { id: 'po:track_delivery', label: 'Track Delivery', description: 'Monitor shipment status', category: 'PURCHASE_ORDERS' },
  { id: 'po:print', label: 'Print PO', description: 'Generate PO PDF', category: 'PURCHASE_ORDERS' },
  { id: 'po:view_payments', label: 'View Payments', description: 'See payment status for PO', category: 'PURCHASE_ORDERS' },
  { id: 'po:manage_terms', label: 'Manage Terms', description: 'Edit PO terms and conditions', category: 'PURCHASE_ORDERS' },
  { id: 'po:link_variation', label: 'Link Variation', description: 'Link PO to contract variation', category: 'PURCHASE_ORDERS' },
  { id: 'po:amend', label: 'Amend PO', description: 'Create PO amendments', category: 'PURCHASE_ORDERS' },
  { id: 'po:audit', label: 'PO Audit', description: 'View history of PO changes', category: 'PURCHASE_ORDERS' },

  // 10. Warehouse & Stock
  { id: 'stock:view', label: 'View Stock', description: 'See current inventory levels', category: 'WAREHOUSE' },
  { id: 'stock:grn_step1', label: 'GRN Step 1', description: 'Record initial receipt of goods', category: 'WAREHOUSE' },
  { id: 'stock:grn_step2', label: 'GRN Step 2', description: 'Finalize GRN and update stock', category: 'WAREHOUSE' },
  { id: 'stock:issue', label: 'Issue Stock', description: 'Record stock issuance to site', category: 'WAREHOUSE' },
  { id: 'stock:return', label: 'Return Stock', description: 'Record returns from site', category: 'WAREHOUSE' },
  { id: 'stock:transfer', label: 'Transfer Stock', description: 'Move stock between locations', category: 'WAREHOUSE' },
  { id: 'stock:adjust', label: 'Adjust Stock', description: 'Manual stock corrections', category: 'WAREHOUSE' },
  { id: 'stock:view_history', label: 'View History', description: 'See stock movement logs', category: 'WAREHOUSE' },
  { id: 'stock:low_alert', label: 'Low Stock Alert', description: 'Manage reorder triggers', category: 'WAREHOUSE' },
  { id: 'stock:view_location', label: 'View Locations', description: 'Manage warehouse bins/sections', category: 'WAREHOUSE' },
  { id: 'stock:audit_count', label: 'Audit Count', description: 'Record physical stock counts', category: 'WAREHOUSE' },
  { id: 'stock:dispose', label: 'Dispose Stock', description: 'Record damaged/expired stock', category: 'WAREHOUSE' },

  // 11. Financials & Variations
  { id: 'fin:view_cost', label: 'View Costs', description: 'See project cost breakdown', category: 'FINANCIALS' },
  { id: 'fin:view_budget', label: 'View Budget', description: 'See project budget status', category: 'FINANCIALS' },
  { id: 'fin:edit_budget', label: 'Edit Budget', description: 'Modify project budgets', category: 'FINANCIALS' },
  { id: 'fin:approve_budget', label: 'Approve Budget', description: 'Final budget approval', category: 'FINANCIALS' },
  { id: 'fin:claim_create', label: 'Create Claim', description: 'Generate payment claims', category: 'FINANCIALS' },
  { id: 'fin:claim_view', label: 'View Claims', description: 'See all project claims', category: 'FINANCIALS' },
  { id: 'fin:claim_approve', label: 'Approve Claim', description: 'Final claim approval', category: 'FINANCIALS' },
  { id: 'fin:var_create', label: 'Create Variation', description: 'Generate variation orders', category: 'FINANCIALS' },
  { id: 'fin:var_view', label: 'View Variations', description: 'See all project variations', category: 'FINANCIALS' },
  { id: 'fin:var_approve', label: 'Approve Variation', description: 'Final variation approval', category: 'FINANCIALS' },
  { id: 'fin:eot_create', label: 'Create EoT', description: 'Generate Extension of Time claims', category: 'FINANCIALS' },
  { id: 'fin:eot_view', label: 'View EoT', description: 'See all EoT claims', category: 'FINANCIALS' },
  { id: 'fin:subcon_agree', label: 'Subcon Agreement', description: 'Manage subcon payment terms', category: 'FINANCIALS' },
  { id: 'fin:subcon_pay', label: 'Subcon Payment', description: 'Approve subcon certificates', category: 'FINANCIALS' },
  { id: 'fin:committed', label: 'View Committed', description: 'See committed cost (POs)', category: 'FINANCIALS' },
  { id: 'fin:actual', label: 'View Actuals', description: 'See actual cost (Invoices)', category: 'FINANCIALS' },
  { id: 'fin:cashflow', label: 'View Cashflow', description: 'See project cashflow forecast', category: 'FINANCIALS' },
  { id: 'fin:export', label: 'Export Financials', description: 'Export cost data to Excel', category: 'FINANCIALS' },
  { id: 'fin:manage_rates', label: 'Manage Rates', description: 'Edit project-specific rates', category: 'FINANCIALS' },
  { id: 'fin:match_invoice', label: 'Match Invoice', description: 'Link invoices to POs/GRNs', category: 'FINANCIALS' },
  { id: 'fin:audit', label: 'Financial Audit', description: 'View history of cost changes', category: 'FINANCIALS' },

  // 12. Supplier Management
  { id: 'sup:view_global', label: 'View Global Suppliers', description: 'Access platform-wide vendor list', category: 'SUPPLIERS' },
  { id: 'sup:view_company', label: 'View Company Suppliers', description: 'See company-specific vendors', category: 'SUPPLIERS' },
  { id: 'sup:manage', label: 'Manage Suppliers', description: 'CRUD operations on vendors', category: 'SUPPLIERS' },
  { id: 'sup:rate', label: 'Rate Supplier', description: 'Submit vendor performance ratings', category: 'SUPPLIERS' },
  { id: 'sup:view_history', label: 'View History', description: 'See vendor transaction history', category: 'SUPPLIERS' },
  { id: 'sup:categories', label: 'Manage Categories', description: 'Configure vendor categories', category: 'SUPPLIERS' },
  { id: 'sup:compliance', label: 'Manage Compliance', description: 'Track vendor certifications/docs', category: 'SUPPLIERS' },
  { id: 'sup:blacklist', label: 'Blacklist Supplier', description: 'Suspend vendors from bidding', category: 'SUPPLIERS' },
  { id: 'sup:contacts', label: 'Manage Contacts', description: 'Edit vendor contact persons', category: 'SUPPLIERS' },
  { id: 'sup:regions', label: 'Manage Regions', description: 'Configure vendor service areas', category: 'SUPPLIERS' },
  { id: 'sup:metrics', label: 'View Metrics', description: 'See vendor performance analytics', category: 'SUPPLIERS' },
  { id: 'sup:portal_invite', label: 'Invite to Portal', description: 'Grant vendor portal access', category: 'SUPPLIERS' },
  { id: 'sup:global_edit', label: 'Edit Global Suppliers', description: 'Modify global library (God only)', category: 'SUPPLIERS' },
  { id: 'sup:archive', label: 'Archive Supplier', description: 'Deactivate vendor profiles', category: 'SUPPLIERS' },
  { id: 'sup:audit', label: 'Supplier Audit', description: 'View history of vendor changes', category: 'SUPPLIERS' },

  // 13. Approval Chains
  { id: 'appr:view_chains', label: 'View Chains', description: 'See approval workflow definitions', category: 'APPROVALS' },
  { id: 'appr:manage', label: 'Manage Chains', description: 'CRUD operations on workflows', category: 'APPROVALS' },
  { id: 'appr:load_global', label: 'Load Global Chains', description: 'Import platform standard chains', category: 'APPROVALS' },
  { id: 'appr:set_logic', label: 'Set Logic', description: 'Configure conditional triggers', category: 'APPROVALS' },
  { id: 'appr:view_pending', label: 'View Pending', description: 'See items awaiting approval', category: 'APPROVALS' },
  { id: 'appr:approve', label: 'Approve Item', description: 'Submit approval for an item', category: 'APPROVALS' },
  { id: 'appr:reject', label: 'Reject Item', description: 'Submit rejection for an item', category: 'APPROVALS' },
  { id: 'appr:delegate', label: 'Delegate Approval', description: 'Assign approval to another user', category: 'APPROVALS' },
  { id: 'appr:view_instances', label: 'View Instances', description: 'See active approval processes', category: 'APPROVALS' },
  { id: 'appr:escalate', label: 'Escalate Approval', description: 'Move item up the chain', category: 'APPROVALS' },
  { id: 'appr:view_history', label: 'View History', description: 'See audit log of approvals', category: 'APPROVALS' },
  { id: 'appr:set_deadlines', label: 'Set Deadlines', description: 'Configure approval SLAs', category: 'APPROVALS' },
  { id: 'appr:bypass', label: 'Bypass Approval', description: 'Force approve (Admin only)', category: 'APPROVALS' },
  { id: 'appr:notify', label: 'Manage Notifications', description: 'Configure approval alerts', category: 'APPROVALS' },
  { id: 'appr:archive', label: 'Archive Chain', description: 'Deactivate workflows', category: 'APPROVALS' },
  { id: 'appr:audit', label: 'Approval Audit', description: 'View history of chain changes', category: 'APPROVALS' },

  // 14. User & Company Admin
  { id: 'admin:view_users', label: 'View Users', description: 'See all company users', category: 'ADMIN' },
  { id: 'admin:create_user', label: 'Create User', description: 'Invite new users to company', category: 'ADMIN' },
  { id: 'admin:edit_user', label: 'Edit User', description: 'Modify user profiles and roles', category: 'ADMIN' },
  { id: 'admin:suspend', label: 'Suspend User', description: 'Deactivate user accounts', category: 'ADMIN' },
  { id: 'admin:view_roles', label: 'View Roles', description: 'See role definitions', category: 'ADMIN' },
  { id: 'admin:create_role', label: 'Create Role', description: 'Define new custom roles', category: 'ADMIN' },
  { id: 'admin:edit_role', label: 'Edit Role', description: 'Modify role capabilities', category: 'ADMIN' },
  { id: 'admin:load_role_profile', label: 'Load Role Profile', description: 'Import standard role templates', category: 'ADMIN' },
  { id: 'admin:override', label: 'User Overrides', description: 'Set specific per-user permissions', category: 'ADMIN' },
  { id: 'admin:view_tenant', label: 'View Tenant', description: 'See company account details', category: 'ADMIN' },
  { id: 'admin:edit_tenant', label: 'Edit Tenant', description: 'Modify company metadata', category: 'ADMIN' },
  { id: 'admin:set_preferences', label: 'Set Preferences', description: 'Configure company-wide settings', category: 'ADMIN' },
  { id: 'admin:view_audit', label: 'View Audit Logs', description: 'See all system activity', category: 'ADMIN' },
  { id: 'admin:view_sessions', label: 'View Sessions', description: 'See active user logins', category: 'ADMIN' },
  { id: 'admin:manage_teams', label: 'Manage Teams', description: 'Group users into functional teams', category: 'ADMIN' },
  { id: 'admin:security', label: 'Security Settings', description: 'Configure MFA/SSO/Password rules', category: 'ADMIN' },
  { id: 'admin:import_users', label: 'Import Users', description: 'Bulk invite from Excel', category: 'ADMIN' },
  { id: 'admin:view_god_logs', label: 'View God Logs', description: 'See activity by Platform God', category: 'ADMIN' },
  { id: 'admin:reset_password', label: 'Reset Password', description: 'Force password reset for user', category: 'ADMIN' },

  // 15. Reports & Dashboards
  { id: 'dash:view', label: 'View Dashboards', description: 'Access project dashboards', category: 'REPORTS' },
  { id: 'dash:create_panel', label: 'Create Panel', description: 'Add new widgets to dashboard', category: 'REPORTS' },
  { id: 'dash:edit_panel', label: 'Edit Panel', description: 'Modify dashboard layout/widgets', category: 'REPORTS' },
  { id: 'dash:load_preset', label: 'Load Presets', description: 'Load standard dashboard templates', category: 'REPORTS' },
  { id: 'dash:share', label: 'Share Dashboard', description: 'Grant access to custom panels', category: 'REPORTS' },
  { id: 'dash:export', label: 'Export Reports', description: 'Generate PDF/Excel reports', category: 'REPORTS' },
  { id: 'dash:view_portfolio', label: 'View Portfolio', description: 'See cross-project analytics', category: 'REPORTS' },
  { id: 'dash:set_home', label: 'Set Home View', description: 'Configure default dashboard', category: 'REPORTS' },
  { id: 'dash:manage', label: 'Manage Dashboards', description: 'CRUD operations on dashboards', category: 'REPORTS' },
  { id: 'dash:view_kpi', label: 'View KPIs', description: 'See key performance indicators', category: 'REPORTS' },

  // 16. Global Library (Platform God Only)
  { id: 'god:lib_role', label: 'Manage Global Roles', description: 'Edit platform standard roles', category: 'GOD_MODE' },
  { id: 'god:lib_appr', label: 'Manage Global Approvals', description: 'Edit platform standard chains', category: 'GOD_MODE' },
  { id: 'god:lib_alert', label: 'Manage Global Alerts', description: 'Edit platform standard alerts', category: 'GOD_MODE' },
  { id: 'god:lib_dash', label: 'Manage Global Dashboards', description: 'Edit platform standard panels', category: 'GOD_MODE' },
  { id: 'god:lib_boq', label: 'Manage Global BOQ', description: 'Edit platform standard BOQ templates', category: 'GOD_MODE' },
  { id: 'god:lib_check', label: 'Manage Global Checklists', description: 'Edit platform standard checklists', category: 'GOD_MODE' },
  { id: 'god:lib_trade', label: 'Manage Global Trades', description: 'Edit platform trade library', category: 'GOD_MODE' },
  { id: 'god:lib_res', label: 'Manage Global Resources', description: 'Edit platform resource library', category: 'GOD_MODE' },
  { id: 'god:lib_sup', label: 'Manage Global Suppliers', description: 'Edit platform supplier library', category: 'GOD_MODE' },
  { id: 'god:lib_version', label: 'Manage Versions', description: 'Configure platform versioning', category: 'GOD_MODE' },
  { id: 'god:lib_publish', label: 'Publish Library', description: 'Push updates to all tenants', category: 'GOD_MODE' },
  { id: 'god:lib_audit', label: 'God Audit', description: 'View history of platform changes', category: 'GOD_MODE' },

  // 17. Company Management (Platform God Only)
  { id: 'god:tenant_create', label: 'Create Tenant', description: 'Provision new company accounts', category: 'GOD_MODE' },
  { id: 'god:tenant_suspend', label: 'Suspend Tenant', description: 'Deactivate company accounts', category: 'GOD_MODE' },
  { id: 'god:tenant_view_all', label: 'View All Tenants', description: 'See all companies on platform', category: 'GOD_MODE' },
  { id: 'god:tenant_bypass_rls', label: 'Bypass RLS', description: 'Access data across tenants', category: 'GOD_MODE' },
  { id: 'god:tenant_clone', label: 'Clone Tenant', description: 'Duplicate company configurations', category: 'GOD_MODE' },
  { id: 'god:tenant_stats', label: 'Tenant Stats', description: 'See usage metrics per company', category: 'GOD_MODE' },
  { id: 'god:tenant_reset', label: 'Reset Tenant', description: 'Clear all data for a company', category: 'GOD_MODE' },
  { id: 'god:tenant_support', label: 'Support Access', description: 'Impersonate tenant users', category: 'GOD_MODE' },
  { id: 'god:tenant_db', label: 'Database Admin', description: 'Manage tenant-specific schemas', category: 'GOD_MODE' },
  { id: 'god:tenant_limits', label: 'Manage Limits', description: 'Set user/project/storage quotas', category: 'GOD_MODE' },
  { id: 'god:tenant_audit', label: 'Tenant Audit', description: 'View history of tenant changes', category: 'GOD_MODE' },
  { id: 'god:tenant_manage_admin', label: 'Manage Tenant Admin', description: 'Edit company owner profiles', category: 'GOD_MODE' },

  // 18. System (Platform God Only)
  { id: 'sys:health', label: 'System Health', description: 'Monitor platform infrastructure', category: 'GOD_MODE' },
  { id: 'sys:config', label: 'System Config', description: 'Edit platform-wide settings', category: 'GOD_MODE' },
  { id: 'sys:backup', label: 'Manage Backups', description: 'Configure automated backups', category: 'GOD_MODE' },
  { id: 'sys:migrate', label: 'Run Migrations', description: 'Execute database schema updates', category: 'GOD_MODE' },
  { id: 'sys:broadcast', label: 'Broadcast Message', description: 'Send alerts to all users', category: 'GOD_MODE' },

  // 19. Field App Guidance
  { id: 'field:view_progress', label: 'View Progress', description: 'See site progress in field app', category: 'FIELD' },
  { id: 'field:view_grouped_progress', label: 'View Grouped Progress', description: 'See progress by section', category: 'FIELD' },
  { id: 'field:view_upcoming', label: 'View Upcoming Tasks', description: 'See field work schedule', category: 'FIELD' },
  { id: 'field:trade_guide_view', label: 'View Trade Guides', description: 'Access field execution manuals', category: 'FIELD' },
  { id: 'field:offline_sync', label: 'Offline Sync', description: 'Manage local data synchronization', category: 'FIELD' },
  { id: 'field:alert_quick', label: 'Quick Alert', description: 'Submit field incidents quickly', category: 'FIELD' },
  { id: 'field:view_baselines', label: 'View Baselines', description: 'See target vs actual in field', category: 'FIELD' },
  { id: 'field:pwa_install', label: 'PWA Install', description: 'Configure mobile app installation', category: 'FIELD' },
];

export const ROLES: Role[] = [
  'platform_god',
  'tenant_admin',
  'contract_admin',
  'director',
  'project_coordinator',
  'project_manager',
  'qs',
  'finance',
  'procurement',
  'site_supervisor',
  'storeman',
  'site_encoder',
  'client'
];
